# Check out https://hub.docker.com/_/node to select a new base image
FROM node:slim

# Create app directory (with user `node`)
RUN mkdir /app; chown node:node /app

# Set to a non-root built-in user `node`
USER node

VOLUME /app
WORKDIR /app

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3000

EXPOSE ${PORT}

ENV PATH="${PATH}:/app/node_modules/.bin/"

CMD npm --loglevel=verbose install; npm start
